### PR TITLE
Handle cancelled Stripe checkout redirects

### LINKED ISSUE #907: Handle cancelled purchase response from Stripe
Right now we just display json on the API, but we should redirect to the front-end and describe what went wrong

### PR DESCRIPTION
**Pull request by neuralsorcerer**
Changes:
- Redirected cancelled Stripe checkout requests to a frontend error page, using client and artist lookups to choose the appropriate destination and providing a reason code for display.
- Added client and artist identifiers to Stripe cancel URLs for catalogue purchases, tips, and subscriptions so the API can generate accurate redirects after a cancellation.
- Created a checkout error view with routing and translations to explain cancelled purchases to users on both artist-specific and global pages.

Why?
- Fixes #907

### CODE REVIEW

**Review by neuralsorcerer — COMMENTED** [review]
In monthly income report job `src/jobs/send-out-monthy-income-report.ts`

- Aggregated the monthly income report by each artist owner, caching user records, skipping owners without deliverable emails or zero revenue, and normalizing sale amounts before dispatching the mail job so multi-artist owners receive a single consolidated email.

File: client/src/components/Checkout/CheckoutError.tsx [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+
+        a {
+          color: var(--color-primary);
+          font-weight: 600;
+        }
+      `}
+    >
+      <h1>{t("title")}</h1>
+      <p>{t(messageKey)}</p>
+      <Link to="/">{t("returnHome")}</Link>
```
Comment (simonv3) [inline client/src/components/Checkout/CheckoutError.tsx]: Do we need this on an artist page?

File: src/routers/v1/checkout/index.ts [hunk 2]
```diff
@@ -3,14 +3,102 @@ import prisma from "@mirlo/prisma";
...
 
   async function GET(req: Request, res: Response, next: NextFunction) {
-    const { success, session_id, stripeAccountId } = req.query;
+    const { success, canceled, session_id, stripeAccountId } = req.query;
     try {
+      if (canceled) {
+        const [clientId, artistId] = [
+          parseNumericQueryParam(req.query.clientId),
+          parseNumericQueryParam(req.query.artistId),
+        ];
```
Comment (simonv3) [inline src/routers/v1/checkout/index.ts]: This feels like it would be much easier to read like this no?
```suggestion
        const clientId = parseNumericQueryParam(req.query.clientId);
        const artistId = parseNumericQueryParam(req.query.artistId);
```

File: src/routers/v1/checkout/index.ts [hunk 3]
```diff
@@ -3,14 +3,102 @@ import prisma from "@mirlo/prisma";
...
+
+        const [client, artist] = await Promise.all([
```
Comment (simonv3) [inline src/routers/v1/checkout/index.ts]: Ditto

File: src/jobs/send-out-monthy-income-report.ts [hunk 4]
```diff
@@ -29,27 +29,92 @@ const sendOutMonthlyIncomeReport = async () => {
...
+      const user = usersById.get(userId);
+
+      if (!user?.email) {
+        logger.warn(
+          `Skipping monthly income report for artist owner ${userId} because no email address was found.`
+        );
+        continue;
+      }
+
+      const normalizedSales = userSales.map((sale) => ({
```
Comment (simonv3) [inline src/jobs/send-out-monthy-income-report.ts]: I don't think amount can be anything other than a number because it comes from the database. So this feels unnecessary to me.

File: src/jobs/send-out-monthy-income-report.ts [hunk 5]
```diff
@@ -29,27 +29,92 @@ const sendOutMonthlyIncomeReport = async () => {
       orderBy: { datePurchased: "asc" },
     });
 
-    const mappedArtists = keyBy(allArtists, "id");
```
Comment (simonv3) [inline src/jobs/send-out-monthy-income-report.ts:32]: It's not clear to me what this does that wasn't already happening? It was already grouping all sales for a single user and it feels much more verbose and harder to track.

File: src/routers/v1/checkout/index.ts [hunk 6]
```diff
@@ -38,15 +124,14 @@ export default function () {
           tipId: string | null;
         };
         if (clientId && artistId) {
-          const client = await prisma.client.findFirst({
-            where: {
-              id: +clientId,
-            },
+          const clientPromise = prisma.client.findUnique({
```
Comment (simonv3) [inline src/routers/v1/checkout/index.ts]: could we `await` these directly?

File: src/routers/v1/checkout/index.ts [hunk 7]
```diff
@@ -3,14 +3,100 @@ import prisma from "@mirlo/prisma";
...
 
   async function GET(req: Request, res: Response, next: NextFunction) {
-    const { success, session_id, stripeAccountId } = req.query;
+    const { success, canceled, session_id, stripeAccountId } = req.query;
     try {
+      if (canceled) {
+        const clientId = parseNumericQueryParam(req.query.clientId);
+        const artistId = parseNumericQueryParam(req.query.artistId);
+
+        const clientPromise = clientId
```
Comment (simonv3) [inline src/routers/v1/checkout/index.ts]: Could we await these directly?

File: src/routers/v1/checkout/index.ts (hunk 6 above)
Comment (neuralsorcerer) [reply src/routers/v1/checkout/index.ts]: Updated

File: src/routers/v1/checkout/index.ts (hunk 7 above)
Comment (neuralsorcerer) [reply src/routers/v1/checkout/index.ts]: Updated.
