### PR TITLE
fix(client): default merch home country to the artist location

### LINKED ISSUE #1974: Default merch destination to the one of the label.
> Also, small suggestion. When I go to create merch, it auto selects the first destination (Afghanistan) as the home destination for shipping. It'd be cool if the destination that appeared was the location set for the label (or artist if using their own page for merch).

### PR DESCRIPTION
**Pull request by peterklingelhofer**
Closes #1974

### CODE REVIEW

File: client/src/components/ManageArtist/Merch/MerchDestinations.tsx [hunk 1]
```diff
@@ -42,13 +55,26 @@ const MerchDestinations: React.FC<{}> = () => {
     queryManagedMerch(merchParamId ?? "")
   );
 
+  const artistCountryCode = React.useMemo(() => {
```
Comment (simonv3) [inline client/src/components/ManageArtist/Merch/MerchDestinations.tsx:58]: Hmm, this is interesting. I guess it's fine. I wonder if people will notice / complain / have weird edge cases.

**Review by simonv3 — APPROVED** [review]
