### PR TITLE
fix: Auto purchase albums release vs publish mixup, test

### LINKED ISSUE #1598: autoPurchaseAlbums not working
We should write a test for this

### PR DESCRIPTION
**Pull request by peterklingelhofer**
Closes #1598

### CODE REVIEW

File: src/jobs/trigger-auto-purchase-new-albums.ts [hunk 1]
```diff
@@ -3,22 +3,22 @@ import logger from "../logger";
...
  */
 export async function triggerAutoPurchaseNewAlbums() {
   const currentDate = new Date();
-  const oneHourAgo = new Date();
-  oneHourAgo.setHours(currentDate.getHours() - 1);
+  const oneHourAgo = new Date(currentDate.getTime() - 60 * 60 * 1000);
 
   const recentAlbums = await prisma.trackGroup.findMany({
     where: {
-      releaseDate: {
```
Comment (simonv3) [inline src/jobs/trigger-auto-purchase-new-albums.ts:17]: I _thiiiink_ this is going to be reworked in @LouisLouiseKay album flow rejig, and I also think we still only want to check for release dates in the past?

**Review by simonv3 — APPROVED** [review]
