### PR TITLE
Fix subscription tier button text spacing issue

### LINKED ISSUE #1559: If already subscribed, button concatenates both sentences
Image

Pink-red button here has its two sentences kissing each other with no dots inbetween 👨‍❤️‍💋‍👨

### PR DESCRIPTION
**Pull request by Ani07-05**
- Add space between subscription status and price text to prevent concatenation
- Fix translation syntax error in youAreFollowingThisArtist key

Fixes #1559

### CODE REVIEW

File: client/src/components/common/SupportArtistTiersForm.tsx [hunk 1]
```diff
@@ -131,8 +131,9 @@ const SupportArtistTiersForm: React.FC<{
       >
         {isSubscribedToCurrentTier &&
           (value?.isDefaultTier
-            ? t("youAreFollowingThisArtist, { artistName: artist.name }")
+            ? t("youAreFollowingThisArtist", { artistName: artist.name })
             : t("youAreAlreadySubscribed"))}
+        {isSubscribedToCurrentTier && " "}
```
Comment (simonv3) [inline client/src/components/common/SupportArtistTiersForm.tsx]: I think part of the issue is that it's displaying both options. So I don't think it should show the following options.

So it shouldn't say both "You are already following." and "continueWIthPricing" in the same place.

Comment (Ani07-05) [reply client/src/components/common/SupportArtistTiersForm.tsx]: makes sense , tbf I did think of it but  judging from the comment I thought it was a spacing/concatenation issue, will fix it and make another PR
